language: node_js
node_js:
  - "6"
cache:
  directories:
    - "node_modules"
env:
  - REPO_NAME=pdfjs-box
branches:
  only:
  - master
before_script:
  - rm -rf node_modules/boxes-scroll
  - git config user.email "$GITHUB_MAIL"
  - git config user.name "$GITHUB_USER"
  - npm install
  - npm install -g gulp-cli
script: 
  - git checkout master
  - gulp
deploy:
  - provider: script
    script: npm version patch -m "[ci skip]"
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: git push https://$GITHUB_TOKEN:x-oauth-basic@github.com/$TRAVIS_REPO_SLUG.git master
    skip_cleanup: true
    on:
      branch: master
  - provider: releases
    user: "$GITHUB_USER"
    api_key: "$GITHUB_TOKEN"
    file_glob: true
    file: dist/*
    skip_cleanup: true
    on:
      branch: master
  - provider: npm
    email: "$NPM_MAIL"
    api_key: "$NPM_TOKEN"
    skip_cleanup: true
    on: 
      branch: master
  - provider: script
    script: bower register $REPO_NAME https://github.com/$TRAVIS_REPO_SLUG.git
    skip_cleanup: true
    on: 
      branch: register_bower
