language: node_js
node_js:
  - "6"
cache:
  directories:
    - "node_modules"
branches:
  only:
  - website
before_script:
  - rm -rf node_modules/pdfjs-box
  - npm install
script: 
  - webpack
deploy:
  - provider: pages
    local-dir: public_html
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
      branch: website
