language: node_js
node_js:
  - "6"
cache:
  directories:
    - "node_modules"
env:
  - REPO_NAME=pdfjs-box
branches:
  only:
  - website
before_install:
  - sudo apt-get install lftp
before_script:
  - rm -rf node_modules/boxes-scroll
  - rm -rf node_modules/pdfjs-box
  - git config user.email "$GITHUB_MAIL"
  - git config user.name "$GITHUB_USER"
  - npm install
script: 
  - webpack
deploy:
  - provider: script
    script: lftp sftp://$SFTP_1AND1_HOST -u $SFTP_1AND1_USER,$SFTP_1AND1_PWD -e "lcd public_html; mkdir -p $REPO_NAME; cd $REPO_NAME; mrm *; mput *; bye"
    skip_cleanup: true
    on:
      branch: website
